apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudf
spec:
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
        - name: cloudf
          image: my_flask_image
          imagePullPolicy: Never