apiVersion : apps/v1
kind: Deployment
metadata:
  name: cloudf 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudf
  template:
    metadata:
      labels:
        app: cloudf 
    spec:
      containers:
        - name: cloudf 
          image: gavlab5.azurecr.io/cloudf
          ports:
          - containerPort: 80